name: generate pacman game

on:
  push:   # Runs whenever you push to main branch
    branches:
      - main
  schedule:  # Runs daily at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch:  # Lets you run it manually from Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm install

      - name: Generate Pac-Man graph
        run: npm run build

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
          force_orphan: true
